openapi: 3.2.0
info:
  title: '{{ .ProductName }} Local Server API'
  description: 'A proxy server for integrating with the {{ .ProductName }} platform.


    ## Setup requirements


    1. Authentication is required to perform some operations. Please refer to the [Authentication](https://developers.certifaction.com/en/references/authentication) section to obtain an API Key or token.

    2. Start the local server on the CLI using the command `{{ .CommandName }} server`


    Refer to [our setup guide](https://developers.certifaction.com/en/guides/getting-started-api) to get started.

    '
  version: ''
servers:
- url: http://localhost:{port}
  variables:
    port:
      default: '8081'
security:
- api_key: []
tags:
- name: Server
  description: Check the server's status
paths:
  /health:
    get:
      operationId: server_health_check
      summary: Check server health
      responses:
        200:
          description: Health check response.
          content:
            application/json:
              schema:
                properties:
                  description:
                    type: string
                  service_name:
                    type: string
                  status:
                    type: string
      security: []
      tags:
      - Server
  /ping:
    get:
      summary: Check that the API server is running
      responses:
        200:
          description: The server is up and running.
          content:
            text/plain:
              schema:
                type: string
                enum:
                - pong
      security: []
      tags:
      - Server
components:
  securitySchemes:
    api_key:
      name: Authorization
      in: header
      type: apiKey
