openapi: 3.2.0
info:
  title: '{{ .ProductName }} Local Documents API'
  description: 'A proxy server for integrating with the {{ .ProductName }} platform.


    ## Setup requirements


    1. Authentication is required to perform some operations. Please refer to the [Authentication](https://developers.certifaction.com/en/references/authentication) section to obtain an API Key or token.

    2. Start the local server on the CLI using the command `{{ .CommandName }} server`


    Refer to [our setup guide](https://developers.certifaction.com/en/guides/getting-started-api) to get started.

    '
  version: ''
servers:
- url: http://localhost:{port}
  variables:
    port:
      default: '8081'
security:
- api_key: []
tags:
- name: Documents
  description: Download your documents or remove {{ .ProductName }}'s access to them
paths:
  /delete-access:
    post:
      operationId: remove_access
      summary: Remove {{ .ProductName }}'s access to a file
      requestBody:
        description: The file that you want to remove {{ .ProductName }}'s access for.
        required: true
        content:
          application/pdf: {}
      responses:
        200:
          description: File access was removed successfully.
        400:
          $ref: '#/components/responses/bad_request'
        401:
          $ref: '#/components/responses/unauthorized'
      tags:
      - Documents
  /download:
    get:
      summary: Download files
      parameters:
      - name: file
        description: A Digital Archive URL
        in: query
        required: true
        schema:
          type: string
          format: url
      - name: password
        description: The signature request password, if Privacy 2.0 was enabled
        in: query
        schema:
          type: string
      operationId: download_file
      responses:
        200:
          description: File download content.
          content:
            application/pdf:
              schema:
                type: string
            application/zip:
              schema:
                type: string
        400:
          $ref: '#/components/responses/bad_request'
        401:
          $ref: '#/components/responses/unauthorized'
      security: []
      tags:
      - Documents
components:
  responses:
    unauthorized:
      description: You are not authorized to carry out the operation. Check that your API key is correct.
    bad_request:
      description: The request is not properly formed. For example, the content could not be read.
  securitySchemes:
    api_key:
      name: Authorization
      in: header
      type: apiKey
